CREATE DATABASE IF NOT EXISTS biblioteca
DEFAULT CHARACTER SET utf8;
use biblioteca;
CREATE TABLE IF NOT EXISTS 	Aluno (
ra INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
cpf CHAR(11) NOT NULL,
telefone CHAR(11) NOT NULL
);
CREATE TABLE IF NOT EXISTS Livro (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
isbn CHAR(11) NOT NULL,
nome VARCHAR(45) NOT NULL,
autor VARCHAR(45) NOT NULL,
paginas VARCHAR(45) NOT NULL 
);
CREATE TABLE IF NOT EXISTS 	Colaborador (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
cpf CHAR(11) NOT NULL,
cargo CHAR(45) NOT NULL
);
CREATE TABLE IF NOT EXISTS Emprestimo (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
dataEmprestimo DATETIME NOT NULL,
dataDevolucao DATE NOT NULL,
alunoRa INT,
livroIsbn VARCHAR(20),
colaboradorCpf VARCHAR(14),
FOREIGN KEY (alunoRa) REFERENCES Aluno(ra),
FOREIGN KEY (livroIsbn) REFERENCES Livro(isbn),
FOREIGN KEY (colaboradorCpf) REFERENCES Colaborador(cpf)
);
